/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        gold: {
          DEFAULT: '#C9A84C',
          light: '#E8C97A',
          dark: '#A07830',
        },
        dark: {
          DEFAULT: '#0A0A0A',
          secondary: '#111111',
          card: '#1A1A1A',
          border: '#2A2A2A',
        },
        light: {
          DEFAULT: '#FFFFFF',
          secondary: '#F8F8F8',
          card: '#F0F0F0',
          border: '#E5E5E5',
        },
        text: {
          primary: '#F5F5F5',
          muted: '#8A8A8A',
        },
        uv: {
          dark: '#0A0A0A',
          light: '#F5F5F5',
          accent: '#C9A84C',
          gray: '#8A8A8A',
        },
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'xs':   ['0.75rem',  { lineHeight: '1rem' }],
        'sm':   ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem',     { lineHeight: '1.5rem' }],
        'lg':   ['1.125rem', { lineHeight: '1.75rem' }],
        'xl':   ['1.25rem',  { lineHeight: '1.75rem' }],
        '2xl':  ['1.5rem',   { lineHeight: '2rem' }],
        '3xl':  ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl':  ['2.25rem',  { lineHeight: '2.5rem' }],
        '5xl':  ['3rem',     { lineHeight: '1' }],
        '6xl':  ['3.75rem',  { lineHeight: '1' }],
        '7xl':  ['4.5rem',   { lineHeight: '1' }],
        '8xl':  ['6rem',     { lineHeight: '1' }],
      },
      spacing: {
        '0.5':  '0.125rem',
        '1':    '0.25rem',
        '1.5':  '0.375rem',
        '2':    '0.5rem',
        '2.5':  '0.625rem',
        '3':    '0.75rem',
        '3.5':  '0.875rem',
        '4':    '1rem',
        '5':    '1.25rem',
        '6':    '1.5rem',
        '7':    '1.75rem',
        '8':    '2rem',
        '9':    '2.25rem',
        '10':   '2.5rem',
        '11':   '2.75rem',
        '12':   '3rem',
        '14':   '3.5rem',
        '16':   '4rem',
        '20':   '5rem',
        '24':   '6rem',
        '28':   '7rem',
        '32':   '8rem',
        '36':   '9rem',
        '40':   '10rem',
        '44':   '11rem',
        '48':   '12rem',
        '52':   '13rem',
        '56':   '14rem',
        '60':   '15rem',
        '64':   '16rem',
        '72':   '18rem',
        '80':   '20rem',
        '96':   '24rem',
      },
      maxWidth: {
        'container': '75rem',
        'content':   '60rem',
      },
      borderRadius: {
        'sm':  '0.25rem',
        'md':  '0.375rem',
        'lg':  '0.5rem',
        'xl':  '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      animation: {
        'pulse-gold': 'pulseGold 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        pulseGold: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(201,168,76,0.4)' },
          '50%': { boxShadow: '0 0 0 12px rgba(201,168,76,0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
}
